apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb
  annotations:
    argocd.argoproj.io/sync-wave: "0"   # ensure CM before Deployments
data:
  # the sample uses a simple user in ConfigMap + credentials in Secret
  database-user: piotr
